telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}


news:
  api:
    key: ${NEWS_API_KEY}


bitcoin:
  api:
    url: https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=brl

ibovespa:
  api:
    url: https://brapi.dev/api/quote/%5EBVSP